##
## Русские системные IMAP-папки
##

namespace inbox {
  mailbox "Черновики" {
    auto = subscribe
    special_use = \Drafts
  }

  mailbox "Отправленные" {
    auto = subscribe
    special_use = \Sent
  }

  mailbox "Спам" {
    auto = subscribe
    special_use = \Junk
  }

  mailbox "Корзина" {
    auto = subscribe
    special_use = \Trash
  }

  mailbox "Архив" {
    auto = subscribe
    special_use = \Archive
  }
}
